# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jei-Lun's Coding Lab
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is under developement but will be updated soon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: @Jujul2012Gaming
github_username:  Jei-Lun

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
